[package]
name = "rocket-tut"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.4.10"

[dependencies.rocket_contrib]
version = "0.4.10"
default-features = false
features = ["helmet", "serve"]